Neos:
  Flow:
    log:
      eventSourcedContentRepositoryLegacyLogger:
        backend: Neos\Flow\Log\Backend\FileBackend
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/EventSourcedContentRepositoryLegacyApiUsage.log'
          createParentDirectories: true
          severityThreshold: '%LOG_INFO%'
          maximumLogFileSize: 10485760
          logFilesToKeep: 1
          logMessageOrigin: true
