Neos:
  EventSourcedNeosAdjustments:
    contentDimensions:
      resolution:
        uriPathSegmentDelimiter: '_'
    fusion:
      enableObjectTreeCache: false
  Flow:
    http:
      chain:
        preprocess:
          chain:
            detectContentSubgraph:
              component: Neos\EventSourcedNeosAdjustments\EventSourcedRouting\Http\DetectContentSubgraphComponent
    mvc:
      routes:
        'Neos.Neos': false
        'Neos.EventSourcedNeosAdjustments':
          variables:
            # Set this to an empty string if you prefer URLs without the ".html" suffix
            'defaultUriSuffix': '.html'
