Neos:
  EventSourcedNeosAdjustments:
    # TODO: re-enable cache!!
    fusion:
      enableObjectTreeCache: false
  Flow:
    error:
      debugger:
        ignoredClasses:
          'Neos\\ContentRepository\\Domain\\Model\\NodeType': true
          'Neos\\Eel\\CompilingEvaluator': true
          'Neos\\EventSourcedContentRepository\\Domain\\Projection\\Content\\PropertyCollection': true
          'Neos\\Fusion\\FusionObjects\\Helpers\\FusionPathProxy': true
          'Neos\\ContentRepository\\Domain\\Service\\NodeTypeManager': true
          'Neos\\ContentRepository\\DimensionSpace\\DimensionSpace\\DimensionSpacePoint.*': true
  Neos:
    fusion:
      autoInclude:
        Neos.EventSourcedNeosAdjustments: true
