Neos:
  EventSourcing:
    EventStore:
      stores:
        'ContentRepository_FOO':
          storage: 'Neos\EventSourcing\EventStore\Storage\Doctrine\DoctrineEventStorage'
          listeners:
            'Neos\Neos\.*': true
