Flowpack:
  JobQueue:
    Common:
      queues:
        # By default we use the Fake Queue that doesn't need a background process
        # For better performance/scale you should consider using a proper job queue backend
        # See https://github.com/Flowpack/jobqueue-common for more details
        'neos-contentCacheFlusher':
          className: 'Flowpack\JobQueue\Common\Queue\FakeQueue'
          options:
            async: true


Neos:
  EventSourcedNeosAdjustments:
    # TODO: re-enable cache!!
    fusion:
      enableObjectTreeCache: false
  Flow:
    error:
      debugger:
        ignoredClasses:
          'Neos\\ContentRepository\\Domain\\Model\\NodeType': true
          'Neos\\Eel\\CompilingEvaluator': true
          'Neos\\EventSourcedContentRepository\\Domain\\Projection\\Content\\PropertyCollection': true
          'Neos\\Fusion\\FusionObjects\\Helpers\\FusionPathProxy': true
          'Neos\\ContentRepository\\Domain\\Service\\NodeTypeManager': true
          'Neos\\ContentRepository\\DimensionSpace\\DimensionSpace\\DimensionSpacePoint.*': true
  Neos:
    fusion:
      autoInclude:
        Neos.EventSourcedNeosAdjustments: true
