Neos:
  ESCR:
    Export:
      presets:
        'default':
          parameters:
            sitePackage: []
          fileSystem:
            factory: Neos\ESCR\Export\Filesystem\LocalFilesystemFactory
            options:
              location: 'resource://{parameters.sitePackage}/Private/Content'
          middlewares:
            'asset':
              className: Neos\ESCR\Export\Middleware\Asset\AssetMiddleware
            'events':
              className: Neos\ESCR\Export\Middleware\Event\NeosEventMiddleware
