# This Docker-Compose file eases running testcases, because it starts Mysql and Postgres in a way that you can copy/paste Settings.yaml reliably.
version: '3.5'
services:
  mysql:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: 'db'
      MYSQL_DATABASE: 'neos-behat'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 'db'
      POSTGRES_DB: 'neos-behat'
    ports:
      - 15432:5432



volumes:
  mysql:


